Created basic professor page layout
jeffreyHoelzel/LouiesRatings pull request #46
Opened 2024-10-25 22:05 UTC by LukeBowen85

Added professor page routed through /professor/lastname-firstname. Should connect with database and Chart.js to render professor's full name and a graph of their grade distributions across all classes they taught. Basic placeholders for other features until they get implemented.

2024-10-25 22:21 UTC, Will-78 requested changes
Overall really good just some minor changes to the way the code is written and the fetch request itself.

2024-10-25 22:21 UTC, Will-78 commented on service/app.py
> +        courses = []
Just return the logic on line 119 since this is essentially done here

2024-10-25 22:21 UTC, Will-78 commented on service/app.py
> +    if not courses:
Not needed with comment above

2024-10-25 22:21 UTC, Will-78 commented on service/app.py
> +        logger.info(f"Received request for search by: {request_data}")
Remove this

2024-10-25 22:21 UTC, Will-78 commented on service/app.py
> +        if search_by == 'class_name':
Space these "if" statements for readibility.

2024-10-25 22:21 UTC, Will-78 commented on service/app.py
> +            search_name = request_data.get('instructor_name')
Instead of having .get('instuctor_name' or 'class_name') just do .get(search_by) once and have the if else be the query.

2024-10-25 22:21 UTC, Will-78 commented on service/app.py
> +        elif search_by == 'instructor_name':
Should be an else?

2024-10-25 22:21 UTC, Will-78 commented on web/src/components/ProfessorPage.js
> +        const response = await fetch(`http://localhost:8080/professor?name=${encodeURIComponent(instructorName)}`);
The fetch should be /service/professor?...

2024-10-27 05:43 UTC, SeanGolez approved these changes
Looks good to me

2024-10-27 05:44 UTC, merged